"""empty message

Revision ID: 957aaffc24fd
Revises: 
Create Date: 2021-03-13 20:52:13.646249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957aaffc24fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('shortcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('shortcode', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shortcode')
    )
    op.create_table('redirect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortcode_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shortcode_id'], ['shortcode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redirect')
    op.drop_table('shortcode')
    op.drop_table('url')
    # ### end Alembic commands ###
